# Dependencies
markdown:         Rouge
kramdown:
  input:                     GFM
  auto_ids:                  true
  footnote_nr:               1
  entity_output:             as_char
  toc_levels:                1..6
  smart_quotes:              lsquo,rsquo,ldquo,rdquo
  enable_coderay:            false
  hard_wrap:                 false
  syntax_highlighter:        rouge
  transliterated_header_ids: true
  footnote_backlink:         "&#8617;&#xfe0e;"
highlighter:      rouge

# Setup
title:            博客
tagline:          'By XiaoFeng'
description:      'O ever youthful, O ever weeping'
url:              https://fongandrew.github.io/hydeout
baseurl:          # the optional subpath of your site, e.g. "/blog"

author:
  name:           'Andrew Fong'
  url:            https://twitter.com/fongandrewc

paginate:         2

plugins:
  - jekyll-feed
  - jekyll-gist
  - jekyll-paginate

# Custom vars
version:            3.4.1
sidebar_home_link:  true
github:
  repo:             https://github.com/ericdxf/ericdxf.github.io

theme: jekyll-theme-cayman